# Шаблон release notes при публикации тега на GitHub.
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - dependencies
      - ignore-for-release
  categories:
    - title: Добавлено
      labels:
        - enhancement
        - feature
    - title: Исправлено
      labels:
        - bug
        - fix
    - title: Прочее
      labels:
        - "*"
